"""add impression_count to click_metric

Revision ID: 8c61b6502326
Revises: a529c908c394
Create Date: 2026-07-18 16:02:01.343627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c61b6502326'
down_revision: Union[str, Sequence[str], None] = 'a529c908c394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click_metric', sa.Column('impression_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('click_metric', 'impression_count')
    # ### end Alembic commands ###
